### PR TITLE
`EntitlementInfo`: fixed `unsubscribeDetectedAt` typo

### LINKED ISSUE #340: [Bug] Incorrect Attribute Name mapping for iOS
## Common project specific issues

There are certain project specific issues that are commonly misinterpreted as bugs.

- [Offerings, products, or available packages are empty](https://support.revenuecat.com/hc/en-us/articles/360041793174)
- [Invalid Play Store credentials errors](https://support.revenuecat.com/hc/en-us/articles/360046398913)
- [Unable to connect to the App Store (STORE_PROBLEM) errors](https://support.revenuecat.com/hc/en-us/articles/360046399333)

For support I'd recommend our [online community](https://spectrum.chat/revenuecat), [StackOverflow](https://stackoverflow.com/tags/revenuecat/) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍

If you have a clearly defined bug (with a [Minimal, Complete, and Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)) that is not specific to your project, follow the steps below to file it with RevenueCat. For SDK-related bugs, make sure they can be reproduced on a physical device, not a simulator (there are simulator-specific problems that prevent purchases from working).

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Environment
    1. Platform: **iOS**
    2. SDK version: **latest and previous**
    3. OS version: **all**
    4. XCode/Android Studio version: **n/a**
    5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue **n/a**
3. Steps to reproduce, with a description of expected vs. actual behavior

In the below location of the code base, there seems to be an inadvertent attribute name mapping error for iOS:

https://github.com/RevenueCat/purchases-hybrid-common/blob/main/ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift#L29-L30

_Expected Behaviour_

Attribute names are: `unsubscribeDetectedAt` and `unsubscribeDetectedAtMillis`

_Actual Behavior_

The attribute names mapped to us past tense, i.e. `unsubscribed`, therefore they are mapped to `unsubscribedDetectedAt` and `unsubscribedDetectedAtMillis` which deviates from the published API contract (and the Android equivalent).

5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #340

### CODE REVIEW

File: ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift [hunk 1]
```diff
@@ -26,8 +26,8 @@ import RevenueCat
             "store": storeString,
             "productIdentifier": productIdentifier,
             "isSandbox": isSandbox,
-            "unsubscribedDetectedAt": unsubscribeDetectedAt?.rc_formattedAsISO8601() ?? NSNull(),
-            "unsubscribedDetectedAtMillis": unsubscribeDetectedAt?.rc_millisecondsSince1970AsDouble() ?? NSNull(),
+            "unsubscribeDetectedAt": unsubscribeDetectedAt?.rc_formattedAsISO8601() ?? NSNull(),
+            "unsubscribeDetectedAtMillis": unsubscribeDetectedAt?.rc_millisecondsSince1970AsDouble() ?? NSNull(),
```
Comment (vegaro) [inline ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: This is a breaking change for React Native and Cordova, since these get transformed directly into Javascript objects. We have typescript definitions, but using typescript is not mandatory. Should we maybe return both this wrong version and the correct one?

What do you think?

Comment (tonidero) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: Oh so it wasn't working at all before?

**Review by tonidero — APPROVED** [review]

File: ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift (hunk 1 above)
Comment (NachoSoto) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: Nope. That's what I meant by the need for end-to-end tests so we can catch this stuff.

Comment (vegaro) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: Our React Native and Cordova plugins just provide Typescript interfaces, we don't do any parsing. This will break anyone that's not using typescript and instead looked at the Javascript object directly, saw we were sending 'unsubscribed' and is accessing that key in the JavaScript object we send down.

It is not very probable anyone is doing that and probably safe to change, but wanted to point out this breaks whoever is accessing that key directly.

In the past, I've kept both versions for a while just in case

Comment (NachoSoto) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: > It is not very probable anyone is doing that and probably safe to change, but wanted to point out this breaks whoever is accessing that key directly.

Oooh I see what you're saying.
We could offer both, but given that those users are using a key that wasn't documented, maybe it's fine. What do you think?

Comment (vegaro) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: Sure, makes sense. Let's ship it!

Comment (NachoSoto) [reply ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift:30]: Thanks!
